[build]
  publish = "dist"
  command = "npm run build"

# Configuración específica para Astro
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Configuración para formularios (si tienes el componente Formulario)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Plugin de Lighthouse (opcional)
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # Configuración del plugin
  [plugins.inputs]
    # Umbral mínimo de performance (0-100)
    performance_threshold = 80
    # Umbral mínimo de accessibility 
    accessibility_threshold = 90
    # Umbral mínimo de best practices
    best_practices_threshold = 90
    # Umbral mínimo de SEO
    seo_threshold = 90